# Site
name: 'Indie Hacking'
description: 'Indie Hacking'
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
avatar: 'assets/images/sal.jpg'
disqus: ''
email: 'hello@vividac.com'

include: ["_pages"]
permalink: /:title/

# Plugins1
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-menus
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
      
# Syntax
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 20


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]

# Collections
collections:
  products:
    output: true
    permalink: /:collection/:categories:output_ext
